version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    groups:
      python:
        patterns: ['*']
        exclude-patterns:
          - openai

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    groups:
      actions:
        patterns: ['*']
