name: findrepo2-experiment

channels:
  - conda-forge

dependencies:
  - python=3.11
  - attrs
  - beautifulsoup4
  - colorama
  - fabric
  - ipykernel
  - msgpack-numpy
  - msgpack-python
  - numpy
  - openai
  - pandas
  - pip
  - requests
  - types-colorama

  # For openai.embeddings_utils (move above if used directly)
  - matplotlib
  - plotly
  - scikit-learn
  - scipy
  - tenacity

  # Dependencies for tiktoken
  - blobfile>=2
  - regex>=2022.1.18

  # Development tools (not needed to run the code)
  - flake8
  - mypy
  - pylint
  - pyright

  # Unavailable via conda (for some CPython version/architecture that we need)
  - pip:
    - blake3
    - tiktoken
