name: findrepo2-experiment

channels:
  - conda-forge

dependencies:
  - python=3.11
  - attrs
  - beautifulsoup4
  - colorama
  - conda-build
  - fabric
  - ipykernel
  - msgpack-numpy
  - msgpack-python
  - nptyping
  - numpy
  - openai
  - pandas
  - pip
  - requests
  - tabulate

  # For openai.embeddings_utils (move above if used directly)
  - matplotlib
  - plotly
  - scikit-learn
  - scipy
  - tenacity

  # Dependencies for tiktoken
  - blobfile>=2
  - regex>=2022.1.18

  # For Jupyter notebooks (beyond the required ipykernel listed above)
  - ipython>=8.10
  - jupyterlab>=3.1

  # Development tools (not needed to run the code)
  - flake8
  - mypy
  - pylint
  - pyright
  - types-colorama
  - types-requests

  # Unavailable via conda (for some CPython version/architecture that we need)
  - pip:
    - blake3
    - tiktoken
    - types-beautifulsoup4
