name: findrepo2-experiment

channels:
  - conda-forge

dependencies:  # FIXME: Check if html5lib and lxml are really needed.
  - python=3.11
  - attrs
  - beautifulsoup4
  - colorama
  - conda-build
  - fabric
  - html5lib
  - ipykernel
  - lxml
  - msgpack-numpy
  - msgpack-python
  - nptyping
  - numpy
  - openai
  - pandas
  - pip
  - requests>=2.31.0
  - tabulate

  # Dependencies for tiktoken
  - blobfile>=2
  - regex>=2022.1.18

  # For Jupyter notebooks (beyond the required ipykernel listed above)
  - ipython>=8.10
  - jupyterlab>=3.1

  # Development tools (not needed to run the code)
  - flake8
  - mypy
  - pylint
  - pyright
  - types-colorama
  - types-requests

  # Unavailable via conda (for some CPython version/architecture that we need)
  - pip:
    - blake3
    - tiktoken
    - types-beautifulsoup4
