[tool.poetry]
name = "findrepo2-experiment"
version = "0.1.0"
description = ""
authors = ["Eliah Kagan <degeneracypressure@gmail.com>"]
license = "0BSD"
readme = "README.md"
packages = [{include = "fr2ex"}]

[tool.poetry.dependencies]
python = "~3.11"
attrs = "^22.2.0"
beautifulsoup4 = "^4.12.0"
blake3 = "^0.3.3"
colorama = "^0.4.6"
fabric = "^3.0.0"
html5lib = "^1.1"
ipykernel = "^6.22.0"
lxml = "^4.9.2"
msgpack-numpy = "^0.4.8"
msgpack-python = "^0.5.6"
nptyping = "^2.5.0"
numpy = "^1.24.3"
openai = {extras = ["embeddings"], version = "^0.27.2"}
pandas = "^1.5.3"
requests = "^2.28.2"
tabulate = "^0.9.0"
tiktoken = "^0.3.3"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
mypy = "^1.1.1"
pylint = "^2.17.1"
pyright = "^1.1.301"
types-beautifulsoup4 = "^4.12.0.1"
types-colorama = "^0.4.15.11"
types-requests = "^2.28.11.17"


[tool.poetry.group.notebook.dependencies]
ipython = "^8.12.0"
jupyterlab = "^3.6.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
