[tool.poetry]
name = "findrepo2-experiment"
version = "0.1.0"
description = ""
authors = ["Eliah Kagan <degeneracypressure@gmail.com>"]
license = "0BSD"
readme = "README.md"
packages = [{include = "fr2ex"}]

[tool.poetry.dependencies]
python = "~3.11"
attrs = "^23.1.0"
beautifulsoup4 = "^4.12.2"
blake3 = "^0.3.3"
colorama = "^0.4.6"
fabric = "^3.1.0"
html5lib = "^1.1"
ipykernel = "^6.23.1"
lxml = "^4.9.2"
msgpack-numpy = "^0.4.8"
msgpack-python = "^0.5.6"
nptyping = "^2.5.0"
numpy = "^1.24.3"
openai = {extras = ["embeddings"], version = "^0.27.7"}
pandas = "^2.0.2"
requests = "^2.31.0"
tabulate = "^0.9.0"
tiktoken = "^0.4.0"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
mypy = "^1.3.0"
pylint = "^2.17.4"
pyright = "^1.1.316"
types-beautifulsoup4 = "^4.12.0.5"
types-colorama = "^0.4.15.11"
types-requests = "^2.31.0.1"


[tool.poetry.group.notebook.dependencies]
ipython = "^8.13.2"
jupyterlab = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
