[tool.poetry]
name = "findrepo2-experiment"
version = "0.1.0"
description = ""
authors = ["Eliah Kagan <degeneracypressure@gmail.com>"]
license = "0BSD"
readme = "README.md"
packages = [{include = "fr2ex"}]

[tool.poetry.dependencies]
python = "~3.11"
attrs = "^23.1.0"
beautifulsoup4 = "^4.12.2"
blake3 = "^0.3.3"
colorama = "^0.4.6"
fabric = "^3.2.2"
html5lib = "^1.1"
ipykernel = "^6.25.2"
lxml = "^4.9.3"
more-itertools = "^10.1.0"
msgpack-numpy = "^0.4.8"
msgpack-python = "^0.5.6"
nptyping = "^2.5.0"
numpy = "^1.26.0"
openai = {extras = ["embeddings"], version = "^0.28.1"}
pandas = "^2.1.1"
requests = "^2.31.0"
tabulate = "^0.9.0"
tiktoken = "^0.5.1"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
mypy = "^1.5.1"
pylint = "^2.17.7"
pyright = "^1.1.333"
types-beautifulsoup4 = "^4.12.0.6"
types-colorama = "^0.4.15.12"
types-requests = "^2.31.0.7"


[tool.poetry.group.notebook.dependencies]
ipython = "^8.16.0"
jupyterlab = "^4.0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
