[tool.poetry]
name = "findrepo2-experiment"
version = "0.1.0"
description = ""
authors = ["Eliah Kagan <degeneracypressure@gmail.com>"]
license = "0BSD"
readme = "README.md"
packages = [{include = "fr2ex"}]

[tool.poetry.dependencies]
python = "~3.11"
attrs = "^24.2.0"
beautifulsoup4 = "^4.12.3"
blake3 = "^0.4.1"
colorama = "^0.4.6"
fabric = "^3.2.2"
html5lib = "^1.1"
ipykernel = "^6.29.5"
lxml = "^5.3.0"
more-itertools = "^10.4.0"
msgpack-numpy = "^0.4.8"
msgpack-python = "^0.5.6"
nptyping = "^2.5.0"
numpy = "^1.26.4"
openai = {extras = ["embeddings"], version = "^0.28.1"}
pandas = "^2.2.2"
requests = "^2.32.3"
tabulate = "^0.9.0"
tiktoken = "^0.7.0"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
mypy = "^1.11.2"
pylint = "^3.2.7"
pyright = "^1.1.378"
types-beautifulsoup4 = "^4.12.0.20240511"
types-colorama = "^0.4.15.20240311"
types-requests = "^2.32.0.20240712"


[tool.poetry.group.notebook.dependencies]
ipython = "^8.27.0"
jupyterlab = "^4.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
